# Generated by Django 5.2.7 on 2025-11-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
